---
- name: Enter text to MOTD file
  become: true
  hosts: all

  tasks: 

  - name: Enter content to MOTD 
    copy:
      content: "Welcome the CentOS system"
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
